### ISSUE TITLE
I only ran through the code once, this error occurred, Processing Nikon D3x raw... Executing dpc... Killed，why？thanks

### ISSUE THREAD

**Issue by dongdongzi** [QiuJueqin/fast-openISP#2]
I only ran through the code once, this error occurred,
Processing Nikon D3x raw... Executing dpc... Killed，

why？Looking forward to your reply，thanks

**Comment by QiuJueqin** [comment]
Did you share your machine with other guys? It seems by other reason, not code.

**Comment by dongdongzi** [comment]
Hello, thank you for your reply. I ran the code on the cloud server, and this bug did not appear later on the win computer.
